version: '3'

tasks:
    unit:
        cmds:
            - vendor/bin/phpunit
    sa:
        cmds:
            - vendor/bin/psalm
    sa-info:
        cmds:
            - vendor/bin/psalm --show-info=true
    cs:
        cmds:
            - vendor/bin/phpcs
    csfix:
        cmds:
            - vendor/bin/phpcbf
    checks:
        deps: [ unit, cs, sa ]
